apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-org1
spec:
  selector:
    matchLabels:
      app: ca-org1
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-org1
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: gkeaccess
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gcs-fuse-csi-static-pvc-test
      containers:
        - name: ca-org1
          image: hyperledger/fabric-ca:1.4.9
          imagePullPolicy: "Always"
          command:
            [
              "fabric-ca-server" ,
              "start", "-b" ,"admin:adminpw","--port","7054", "-d"
            ]
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
          env:
           - name: FABRIC_CA_SERVER_CA_NAME
             value: ca-org1
           - name: FABRIC_CA_SERVER_TLS_ENABLED
             value: "true"
           - name: FABRIC_CA_SERVER_CSR_CN
             value: "ca-org1"
           - name: FABRIC_CA_SERVER_CSR_HOSTS
             value: "ca-org1"
          volumeMounts:
            - name: data
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/org1
---
apiVersion: v1
kind: Service
metadata:
  name: ca-org1
  labels:
    app: ca-org1
spec:
  type: ClusterIP
  selector:
    app: ca-org1
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054