apiVersion: batch/v1
kind: Job
metadata:
  name: artifacts
spec:
  template:
    metadata:
      name: create-genesis-block
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: gkeaccess
      containers:
        - name: artifacts
          image: hyperledger/fabric-tools:2.3
          workingDir: /
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /configtx
              name: fabricfiles
              subPath: configtx
            - mountPath: /system-genesis-block
              name: fabricfiles
              subPath: system-genesis-block
            - mountPath: /channel-artifacts
              name: fabricfiles
              subPath: channel-artifacts
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
          command:
            - /bin/bash
            - -c
            - |
              mkdir /tmp/scripts &&
              cp /scripts/* /tmp/scripts/ &&
              echo "Listing /tmp/scripts before chmod" &&
              ls -l /tmp/scripts &&
              chmod a+rwx /tmp/scripts/createGenesis.sh &&
              chmod a+rwx /tmp/scripts/createChannel.sh &&
              echo "Listing /tmp/scripts after chmod" &&
              ls -l /tmp/scripts &&
              /tmp/scripts/createGenesis.sh &&
              /tmp/scripts/createChannel.sh
              echo "Genesis block created..."
      restartPolicy: Never
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: gcs-fuse-csi-static-pvc-test
